# Docker Compose Override for ARM64 Architecture
# This file configures all services for ARM64 compatibility

services:
  # Configurator service - ARM64 platform
  configurator:
    platform: linux/arm64
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
    networks:
      - frappe_network

  # Create-site service - ARM64 platform
  create-site:
    platform: linux/arm64
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
    networks:
      - frappe_network

  # Backend service - ARM64 platform
  backend:
    platform: linux/arm64
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
    networks:
      - frappe_network

  # Frontend service - ARM64 platform
  frontend:
    platform: linux/arm64
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
    networks:
      - frappe_network

  # WebSocket service - ARM64 platform
  websocket:
    platform: linux/arm64
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
    networks:
      - frappe_network

  # Queue services - ARM64 platform
  queue-short:
    platform: linux/arm64
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
    networks:
      - frappe_network

  queue-long:
    platform: linux/arm64
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
    networks:
      - frappe_network

  # Scheduler service - ARM64 platform
  scheduler:
    platform: linux/arm64
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
    networks:
      - frappe_network

    platform: linux/arm64
    volumes:

# Volume configuration remains the same
# ARM64 containers will use the same volume structure
volumes:
  sites:
    driver: local

# Network configuration
networks:
  frappe_network: {}