services:
  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      - traefik.http.routers.frontend-http.entrypoints=web
      - traefik.http.routers.frontend-http.rule=Host(`intralogistics.lab`)
      - traefik.http.routers.frontend-http.priority=100

    # Fixed ports for lab environment
    ports:
      - "502:502"    # MODBUS TCP server
    labels:
      - traefik.enable=true

  proxy:
    image: traefik:v2.11
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --log.level=INFO
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"      # HTTP
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frappe_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`dashboard.intralogistics.lab`)
      - traefik.http.routers.traefik.service=api@internal
    userns_mode: host